### ISSUE TITLE
stash api key should not be mandatory

### ISSUE THREAD

**Issue by ferengi82** [Whisparr/Whisparr#102]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

cant add a stash connection without an api-key

### Expected Behavior

dont force to use api-keys, i dont use a password on my stashapp (and I don't want to) => I have no API key

### Environment

```markdown
- OS: Ubuntu 22.04
- Whisparr: 2.0.0.250
- Docker Install: yes 
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Main

### Trace Logs?

-

**Comment by Qstick** [comment]
Does stash allow utilizing the API without auth or a key? Most apps don't
