### ISSUE TITLE
My own Self-hosted StashBox as metadata source

### ISSUE THREAD

**Issue by aicynide** [Whisparr/Whisparr#116]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Nope

### Describe the solution you'd like

I'll want to do manual labour TPDB corporation 

### Describe alternatives you've considered

Self-hosted metadata source

### Anything else?

You tell

**Comment by Qstick** [comment]
Not in the cards anytime soon
