### ISSUE TITLE
TPDB down - Alternatives?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Whisparr/Whisparr#120]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi,

For the past few days, TPDB - the metadata provider is down. Their website is down too - https://metadataapi.net/

### Expected Behavior

Is there any information on what happened? And whether it's coming back up? If not, will stash db be the only alternative?

### Environment

```markdown
- OS: 
- Whisparr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Main

### Trace Logs?

NA

**Comment by Qstick** [comment]
Website is working fine for me

**Comment by 0ldasdirt** [comment]
Working for you Qstick?  Hasn't accessible to me for many days. I've used VPNs, flushed DNS cache, used 3 different browsers, and 2 different machines with 2 different OSs and no access---just reports Bad Gateway.  I am accessing from VA, but used at least 4 different VPN servers in different states--no access.

**Comment by Gandalf-the-Blue** [comment]
@Qstick Are you maybe seeing Cloudflare's Always Online version of the website?

**Comment by 0ldasdirt** [comment]
An update---Metadataapi.net is working now after nearly 5 days,. If I remember correctly, Cloudflare  stated that the website was down--should've taken a screenshot--I would get presented with a waybackmachine screenshot though sometimes, but not useful.  Anyway, it's working now. Crossing fingers that it keeps on working.  I will note that the site seems to load much faster than it used to.

**Comment by Qstick** [comment]
Yea, unfortunately the API still isnt, Whisparr metadata is still getting constant 502 from TPDB

**Comment by qeasd42** [comment]
It would be beneficial to support other API systems like stash boxes
