### ISSUE TITLE
Monitoring a Series pushed all the scenes of the site to the "Wanted" section

### ISSUE THREAD

**Issue by adlpharm** [Whisparr/Whisparr#127]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Monitoring series trigger all the scenes within the Series to the wanted section even none or some are selected to be monitored

### Expected Behavior

Only the scenes which wants to be monitored should go to the wanted section, not all

### Environment

```markdown
- OS: Docker. Ubuntu server
- Whisparr: 2.0.0.287
- Docker Install:
- Using Reverse Proxy:
- Browser:
- Database:
```

### What branch are you running?

Main

### Trace Logs?

NA

**Comment by adlpharm** [comment]
Same happened to me

**Comment by XXXeraph** [comment]
This may be a filter issue.  

It appears that Unmonitored scenes are showing up in the "Monitored" filter in Wanted.  I flipped a monitored scene to unmonitored in the Wanted queue.  The flag changed from solid to outline, but remained in the wanted queue. I changed the applied filter from Monitored to Unmonitored and back to reset it, but it still remains.  I currently have 994 pages of Wanted scenes.  Going to a site and telling it to ignore everything except future releases appears to have no effect.

Is there some sort of functional change in how the filters work?

Version 2.0.0.287
.NET Yes (6.0.21)
Database Sqlite 3.40.1

**Comment by salesawagner** [comment]
Following

**Comment by salesawagner** [comment]
Now I have more than 22 thousand pages of wanted. And every day it increases more and more! This bug is very serious.
This does not take into account what has already been downloaded

**Comment by Y0US34** [comment]
same issue here, weird behaviour is if i unmonitor the site only the monitored scenes appear in the wanted section but can't dowload them since the whole site is unmonitored

**Comment by StarWing01** [comment]
Same issue here, but I want to monitor 1 scene from 1 site. In Sonarr you can unmonitor a serie/season but random select some episodes marked for download/search. This is currently not possible in Whisparr.

**Comment by Qstick** [comment]
https://github.com/Whisparr/Whisparr/commit/1d98e83f452e8370f922c0af60881eeb63c175c0
