### ISSUE TITLE
Option to bypass whisparr.com cache and load metadataapi directly

### ISSUE THREAD

**Issue by qeasd42** [Whisparr/Whisparr#129]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

whisparr.com cache is frequently broken or out of sync with metadataapi

### Describe the solution you'd like

I would prefer to load metadataapi directly

### Describe alternatives you've considered

Alternatively we could follow the [MusicBrainz](https://wiki.servarr.com/lidarr/faq#i-cannot-find-a-release-in-lidarr-but-it-is-on-musicbrainz) model and open source the whisparr.com cache so people can run a local copy if they want

**Comment by Darklyter** [comment]
And tpdb would appreciate you guys not melting their server with hundreds of people hitting the database directly

**Comment by Qstick** [comment]
Haha, yea, this isn't something we plan to do. TPDB wouldn't be able to handle it
