### ISSUE TITLE
Search all in "wanted" section is not working properly

### ISSUE THREAD

**Issue by adlpharm** [Whisparr/Whisparr#142]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Search all in "wanted" section is not working all the scenes monitored and included in the section. Only try to find some of them. After a search all I perform an automatic search of single scenes and they are grabbed

### Expected Behavior

The search all feature try to find all the scenes included in the wanted section

### Steps To Reproduce

Docker
version: 2.0.0.355
—
02 Jan 2024

### Environment

```markdown
- OS: linux
- Whisparr: Docker
version: 2.0.0.355
- Docker Install: yes
- Using Reverse Proxy: No
```

### What branch are you running?

Main

### Trace Logs?

NA

**Comment by Qstick** [comment]
Not applicable in V3, closing
