### ISSUE TITLE
Allow "Studio Name" in title

### ISSUE THREAD

**Issue by hypstu** [Whisparr/Whisparr#143]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

whisparr is great, but if you're using it with Plex, the existing adult films found in IMDB / TMDB etc are quite limited.

I use a secondary Plex metadata manager specifically for gay content, and it requires a studio title to do proper scraping:

https://github.com/CodyBerenson/PGMA-Modernized/tree/master

if whisparr would allow me to use studio titles, I could automate most of the process

### Describe the solution you'd like

It can be as simple as allow the name title to pull the studio title:

(StudioName) {Movie CleanTitle} ({Release Year})

### Describe alternatives you've considered

I just haven't been able to find luck using anything else, so I've been manually doing most adds

### Anything else?

thanks for developing!

**Comment by Qstick** [comment]
Already in V3 alpha
