### ISSUE TITLE
Add the following Naming Tokens

### ISSUE THREAD

**Issue by thezak48** [Whisparr/Whisparr#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

- 'date' - in the format of YYYY-MM-DD or ability to change the date format (maybe based of UI setting perhaps)
- 'name' - the scene name
- 'site' - the site name, BrazzersExxtra, AllHerLuv, Deeper, etc with spaces removed.
- 'full_site' - the site name from porndb, unmodified, i.e: Brazzers Exxtra, All Her Luv, etc.
- 'performers' - space seperated list of female performers
- 'all_performers' - space seperated list of all performers
- 'network' - the network full site/studio name from porndb, with spaces removed, i.e: MindGeek, Vixen, etc.
- 'full_network' - the network full site/studio name from porndb, unmodified, i.e: Mind Geek, Vixen, etc.

Remove ImdbID

Repalce TmdbID with TpdbID

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by thezak48** [comment]
Parts completed

- 'date' - in the format of YYYY-MM-DD or ability to change the date format (maybe based of UI setting perhaps)
- 'name' - the scene name
- 'full_site' - the site name from porndb, unmodified, i.e: Brazzers Exxtra, All Her Luv, etc.

Remove ImdbID

Repalce TmdbID with TpdbID

**Comment by StPatty33** [comment]
The addition of performer(s) would be super helpful, for sure.

**Comment by adtdev20** [comment]
I'll second that adding a 'performers' tag to the renamer would be really helpful, my naming strategy for plex is usually:

`'full_site' - 'date' - 'performers' - 'name'`

**Comment by StPatty33** [comment]
I saw this issue was closed, but after updating the program there is still no mention of "performer" as a potential option in renaming.

**Comment by Qstick** [comment]
Build with this hasn't completed successfully yet.
