### ISSUE TITLE
tpdb has been shutdown

### ISSUE THREAD

**Issue by wuzhican** [Whisparr/Whisparr#161]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

the https://metadataapi.net/ cannot be access

there is the announce

Site Shutdown Announcement
We regret to inform you that our site is being shut down. We appreciate your support and engagement throughout the years.

However, we have some good news! We will be publishing our dataset soon, so stay tuned for updates.

### Expected Behavior

normal access

### Environment

```markdown
android
```

### What branch are you running?

Main

### Trace Logs?

no log

**Comment by nycedwardd** [comment]
Ideally, stashdb could be configured as a data provider. That's probably the next highest quality data source available.

**Comment by Net005** [comment]
Seems like they will be back in some form or another:

![image 1](https://github.com/Whisparr/Whisparr/assets/11522289/5a54076c-c84d-471a-96c9-e4f7016d7aa5)

**Comment by papampi** [comment]
So any workaround until its coming back?

**Comment by bulletproof2k** [comment]
Perhaps they will post their metadata on some resource.
Does anyone have any information about this?

![2024-03-03_16-51-54](https://github.com/Whisparr/Whisparr/assets/1818579/ed440151-6c1f-4877-a0e7-ab896a8b3612)

**Comment by frankmagon** [comment]
It's back up now @ [https://theporndb.net/](url) everyone should jump on their discord and donate to show your appreciation for their hard work getting it back up and running.

**Comment by bulletproof2k** [comment]
> It's back up now @ [https://theporndb.net/](url) everyone should jump on their discord and donate to show your appreciation for their hard work getting it back up and running.

Thanks for the news :)

**Comment by wuzhican** [comment]
Is it necessary to add other sources of metadata to avoid the same thing from happening

**Comment by iskirb** [comment]
When will we get an TPDB update? The merging seems to be failed status..

**Comment by ranrinc** [comment]
When will this be available to download? I mean the one that fixed the domain? Its seems the merging is failing

**Comment by TheepStar** [comment]
How can i replace the domain in whisparr?

**Comment by andrewmeyer** [comment]
Keep in mind that they are stating they will be login only, it may be beneficial to leverage their API and use tokens to ensure proper auth
