### ISSUE TITLE
UI - SWF Switch

### ISSUE THREAD

**Issue by thezak48** [Whisparr/Whisparr#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

Have a toggle switch or setting that blurs all posters so that it is SFW

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by arth6250** [comment]
There is a FireFox extension called "Blur" that does this, may be useful to you until this feature is implemented.

**Comment by austinwbest** [comment]
> There is a FireFox extension called "Blur" that does this, may be useful to you until this feature is implemented.
> 

I've already built the logic in the SFW branch. Just waiting on Q to review it and then I think Zak was gonna finish it up.
