### ISSUE TITLE
V3: Manual Import and Special Characters

### ISSUE THREAD

**Issue by Eleniatari** [Whisparr/Whisparr#177]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right most special characters are stripped out of file names or replace with periods.

If a special character is present in the final name of the release the manual import is not able to match it unless the user knows it's present.

Example. Recently had difficulty matching a file manually.
Filename:
4K.Character.Name.SexAct
Name in Whisparr:
4K. Character-Name SexAct

The . and - both prevented a match until I figured out what was happening.

### Describe the solution you'd like

Have the 'search' ignore special character matching. Displaying scenes that are interrupted by special characters or not.

### Describe alternatives you've considered

None

### Anything else?

It would be great to have the file name visible while matching.

**Comment by sampulsar** [comment]
@Eleniatari 

Can you provide the folder and file name, plus the stash Id that you expect this to match. Manual imports match on the folder first and then finally try the filename if nothing is matched.

There is a different process used to match a scene if the process is unable to determine a date, but it still attempt to see if it can find a single match based on the title.

There is some normalization of the filename and also the stashdb title to improve the matching of the files.

**Comment by Eleniatari** [comment]
I'll dig one up. Is there a way in a file history to determine if it was an auto match or manual?

**Comment by sampulsar** [comment]
Even when the log level is set at trace level there many not be enough information to determine if you manual selected the matching scene.

**Comment by Eleniatari** [comment]
Okay. Give me a while to find one. Since that's the case the ones I thought did it I can't confirm.

**Comment by Eleniatari** [comment]
None of these would parse through manual import.

```
Name
Reflective Desire - 2022-11-01 - Riah Vespa - Riah vs Vespa - WEBDL-2160p x264
Source
/data/media/xxx v3/Reflective Desire/2022-11-01 - Riah vs Vespa/Reflective Desire - 2022-11-01 - Riah Vespa - Riah vs Vespa - WEBDL-2160p x264.mp4
Imported To
/data/media/xxx/Reflective Desire/2022-11-01 Riah vs Vespa fb7ac892-ebc8-4f82-a1e8-b1cf5c469ca4/Reflective Desire: 2022-11-01 - Riah vs Vespa WEBDL-2160p.mp4
```

```
Name
Reflective Desire - 2022-12-01 - Chuck Faerie Vespa - Pussyfootin' - WEBDL-2160p h264
Source
/data/media/xxx v3/Reflective Desire/2022-12-01 - Pussyfootin'/Reflective Desire - 2022-12-01 - Chuck Faerie Vespa - Pussyfootin' - WEBDL-2160p h264.mp4
Imported To
/data/media/xxx/Reflective Desire/2022-12-01 Pussyfootin' e90165d0-335a-4c14-a382-23754f8213c7/Reflective Desire: 2022-12-01 - Pussyfootin' WEBDL-2160p.mp4
```

```
Name
Reflective Desire - 2023-11-01 - Mbot Vespa - Quickdraw - WEBDL-2160p x264
Source
/data/media/xxx v3/Reflective Desire/2023-11-01 - Quickdraw/Reflective Desire - 2023-11-01 - Mbot Vespa - Quickdraw - WEBDL-2160p x264.mp4
Imported To
/data/media/xxx/Reflective Desire/2023-11-01 Quickdraw bdb5f9c3-1bc0-4cc3-80dc-d5e0c92cd701/Reflective Desire: 2023-11-01 - Quickdraw WEBDL-2160p.mp4
```

```
Name
MollyRedWolf - 2022-04-14 - MollyRedWolf - Komi-San. I want you - WEBDL-720p x265
Source
/data/media/xxx v3/MollyRedWolf/2022-04-14 - Komi-San. I want you/MollyRedWolf - 2022-04-14 - MollyRedWolf - Komi-San. I want you - WEBDL-720p x265.mkv
Imported To
/data/media/xxx/MollyRedWolf/2022-04-14 Komi-San. I want you 698a49ee-3da1-4563-bdc9-5cac2f13b200/MollyRedWolf: 2022-04-14 - Komi-San. I want you WEBDL-720p.mkv
```

This sufficient or want me to keep providing some?

**Comment by sampulsar** [comment]
Looked at one and can explain why it does not currently match.

![image](https://github.com/Whisparr/Whisparr/assets/80544409/95c16961-0b1d-4f5c-a894-dc0497cfa293)
It can determine the the studio and date.
It assume it is a scene as it has a studio and date. The last section may be considered the title in this example.
It looks up the studio and then it finds if there are any on that date in your local database.

If it just finds one then is automatically selects that as the matching scene. (Can be a false positive if the studio is not monitored)
The scene in question has 3 on the same date, so then it needs to check on what the database, Title and performers on the scene, with the title section.

Title needs to match so having performers when the title is "Quickdraw" on stashDB will not match even if it was cleaned to be just Mbot Vespa - Quickdraw.

After that it checks if the title contain any of the performers, this can just be one, and Vespa is in all three, so all three are a match and it does not auto match.

Pussyfootin' is more complex as it has BTS on the same date so that also have the same performers.

Some of the matching is there to stop false positives, and force the user to manually match.

**Comment by Eleniatari** [comment]
That makes sense for the first 3, the last has no other scene for that date that I can find, yet it also didn't match.

Is it just because the performers name was present?

**Comment by sampulsar** [comment]
I tested folder/file this one the latest version and it was able to import.
MollyRedWolf/2022-04-14 - Komi-San. I want you/MollyRedWolf - 2022-04-14 - MollyRedWolf - Komi-San. I want you - WEBDL-720p x265.mkv

Folder "MollyRedWolf" should can not find any scene or movie with this name.
Folder "2022-04-14 - Komi-San. I want you" should can not find any scene or movie with this name
File "MollyRedWolf - 2022-04-14 - MollyRedWolf - Komi-San. I want you - WEBDL-720p x265" gets the studio and the date.
Only one for that date so it should match 

Do you want to try the filename again and change the logging level to Trace, under settings - general

**Comment by Eleniatari** [comment]
I'll look for another one tonight and turn on trace once I find one. Thank you.

**Comment by Eleniatari** [comment]
Failed to process file: /data/usenet/complete/xxx/bex.2023.05.31.mia.molotov.dripping.wet.and.draped.in.latex.4k/bex.2023.05.31.mia.molotov.dripping.wet.and.draped.in.latex.4k.mp4: Value cannot be null. (Parameter 'input')

System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at NzbDrone.Core.Parser.Parser.CleanMovieTitle(String title) in ./Whisparr.Core/Parser/Parser.cs:line 490
   at NzbDrone.Core.Movies.MovieService.FindByTitleCandidates(List`1 titles, List`1& otherTitles) in ./Whisparr.Core/Movies/MovieService.cs:line 146
   at NzbDrone.Core.Movies.MovieService.FindByTitle(String title, Int32 year) in ./Whisparr.Core/Movies/MovieService.cs:line 121
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.ProcessFile(String rootFolder, String baseFolder, String file, String downloadId, Movie movie) in ./Whisparr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 262
Close

Name
bex.2023.05.31.mia.molotov.dripping.wet.and.draped.in.latex.4k
Source
/data/usenet/complete/xxx/bex.2023.05.31.mia.molotov.dripping.wet.and.draped.in.latex.4k/bex.2023.05.31.mia.molotov.dripping.wet.and.draped.in.latex.4k.mp4
Imported To
/data/media/xxx/Brazzers Exxtra/2023-05-31 Dripping Wet And Draped In Latex ec73397d-9ffb-4915-81f7-7de036d19f9d/Brazzers Exxtra: 2023-05-31 - Dripping Wet And Draped In Latex WEBDL-2160p.mp4

Other than that, it seems it's impossible for it to parse with no date even if the studio and title are present. That is correct?

These two titles could not be found via the search. 
Hot For The Job - S2:E2
Flesh: House of Hedonism - Episode 1

I can't seem to get the hyphen to process properly or question marks when copied from search into the find box.

**Comment by Eleniatari** [comment]
2024-03-21 20:51:48.7|Debug|Parser|Parsing string 'Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4'
2024-03-21 20:51:48.7|Trace|Parser|^(?<studiotitle>.+?)?[-_. ]+(?<airyear>\d{2}|\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])
2024-03-21 20:51:48.7|Debug|Parser|Scene Parsed.  - 0 
2024-03-21 20:51:48.7|Debug|Parser|Release Group parsed: 
2024-03-21 20:51:48.7|Debug|Parser|Languages parsed: Unknown
2024-03-21 20:51:48.7|Debug|QualityParser|Trying to parse quality for 'Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4'
2024-03-21 20:51:48.7|Debug|Parser|Quality parsed: WEBDL-1080p v1
2024-03-21 20:51:48.7|Debug|Parser|Edition parsed: 
2024-03-21 20:51:48.7|Debug|Parser|Parsing string 'Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4'
2024-03-21 20:51:48.7|Trace|Parser|^(?<studiotitle>.+?)?[-_. ]+(?<airyear>\d{2}|\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])
2024-03-21 20:51:48.7|Debug|Parser|Scene Parsed.  - 0 
2024-03-21 20:51:48.7|Debug|Parser|Release Group parsed: 
2024-03-21 20:51:48.7|Debug|Parser|Languages parsed: Unknown
2024-03-21 20:51:48.7|Debug|QualityParser|Trying to parse quality for 'Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4'
2024-03-21 20:51:48.7|Debug|Parser|Quality parsed: WEBDL-1080p v1
2024-03-21 20:51:48.7|Debug|Parser|Edition parsed: 
2024-03-21 20:51:48.7|Debug|Parser|Parsing string 'Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4'
2024-03-21 20:51:48.7|Trace|Parser|^(?<studiotitle>.+?)?[-_. ]+(?<airyear>\d{2}|\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])
2024-03-21 20:51:48.7|Debug|Parser|Scene Parsed.  - 0 
2024-03-21 20:51:48.7|Debug|Parser|Release Group parsed: 
2024-03-21 20:51:48.7|Debug|Parser|Languages parsed: Unknown
2024-03-21 20:51:48.7|Debug|QualityParser|Trying to parse quality for 'Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4'
2024-03-21 20:51:48.7|Debug|Parser|Quality parsed: WEBDL-1080p v1
2024-03-21 20:51:48.7|Debug|Parser|Edition parsed: 
2024-03-21 20:51:48.7|Warn|ManualImportService|Failed to process file: /data/media/xxx v2/Digital Playground/2000/Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4

[v3.0.0.503] System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at NzbDrone.Core.Parser.Parser.CleanMovieTitle(String title) in ./Whisparr.Core/Parser/Parser.cs:line 490
   at NzbDrone.Core.Movies.MovieService.FindByTitleCandidates(List`1 titles, List`1& otherTitles) in ./Whisparr.Core/Movies/MovieService.cs:line 146
   at NzbDrone.Core.Movies.MovieService.FindByTitle(String title, Int32 year) in ./Whisparr.Core/Movies/MovieService.cs:line 121
   at NzbDrone.Core.MediaFiles.MovieImport.Manual.ManualImportService.ProcessFile(String rootFolder, String baseFolder, String file, String downloadId, Movie movie) in ./Whisparr.Core/MediaFiles/MovieImport/Manual/ManualImportService.cs:line 262

**Comment by sampulsar** [comment]
bex.2023.05.31.mia.molotov.dripping.wet.and.draped.in.latex.4k
will not work as bex is not Brazzers Exxtra. There is no alias system you can not even search for the studio on stash.org with bex.

I have created a Pull Request that will improve the parsing of the files.

**Comment by Eleniatari** [comment]
The digital playground one it just didn't like? I can't tell what it even tried to do from the trace excerpt. It found the quality, but I can't see it doing anything else other then returning the name was -0?

So far as I can tell it can't parse special characters if you type them into the box. I assume this is because of Unicode font differences?
It can't detect a studio if it's not verbatim?
It can't import if two scenes share the same date?
It does not use the scene name at all?

**Comment by sampulsar** [comment]
It can't detect a studio if it's not verbatim?
Whisparr V3 does not know bex is not Brazzers Exxtra. verbatim works best and the next best is BrazzersExxtra. You can add a feature request if you want aliases like bex to be used in the index search and Import. You may also know if there is anywhere that lists these alias on the internet.

It can't import if two scenes share the same date?
It matches on the title and performers to determine if it can confidentially identify the scene. This will not happen every time as a false positive is the worst thing as it can override an existing file.  

It does not use the scene name at all?
Yes it does, but the current version would have included some extra information at the end "- WEBDL-1080p". The incoming change will strip this off. The scene name also has to be verbatim to match.

You can read the code that will match the scene
https://github.com/Whisparr/Whisparr/blob/eros/src/NzbDrone.Core/Movies/MovieService.cs#L367 

any "-" is removed from the titles.
 var parsedMovieTitle = Parser.Parser.NormalizeEpisodeTitle(releaseTokens)

**Comment by Eleniatari** [comment]
Yet it didn't work for this one.
https://github.com/Whisparr/Whisparr/issues/177#issuecomment-2014172244

That is why I asked the questions because it appears to meet every criteria you listed but no match.

https://stashdb.org/studios/1e8d8028-fb8c-4286-b742-e62e5667c576?page=50
Nothing shares the date. So only reasonable explanation is special characters vs name. As the scene on stash includes a colon but I don't see that stripped or ignored when manually searching after a failed autosearch. 

Or hyper specific matching of studio? If it's the latter I'll put in a request that each studio needs to include all main/subs as matches. 

Studio, Date, Scene name and Quality.

I stated it the way I did because according to the trace, I can't see it even attempted a match.

**Comment by sampulsar** [comment]
https://stashdb.org/scenes/302d6b5e-e5f1-4887-9b12-8296b8703e65
Studio is "Digital Playground Episodes"
Network is "Digital Playground". On stasdb it is part of.

It is a known as the Network in Whisparr.

You should also provide some information of where the origin of the file/folder name, what indexer etc, on your request.

**Comment by sampulsar** [comment]
Looks like stashDB may be adding alias information to studios.

Once this is done Whisparr may be able to be updated to search on any known aliases for a studio. Then you can submit all of your studio aliases to StashDB.

https://github.com/stashapp/stash-box/issues/676

**Comment by Eleniatari** [comment]
> Looks like stashDB may be adding alias information to studios.
> 
> Once this is done Whisparr may be able to be updated to search on any known aliases for a studio. Then you can submit all of your studio aliases to StashDB.
> 
> [stashapp/stash-box#676](https://github.com/stashapp/stash-box/issues/676)

That won't solve the issue. Being called 'DPEpisodes' still wouldn't allow it to parse. It seems that a request should be made that the parse also uses the main network of a sub studio as well as a substudio to achieve a match?

The file in reference from Digital Playground vs Digital Playground Episodes was downloaded by V2 and a file already on my drive. No indexer involved and file path is.

/data/media/xxx v2/Digital Playground/2000/Digital Playground - 2016-05-07 - Flesh House of Hedonism - Episode 1 - WEBDL-1080p.mp4

**Comment by sampulsar** [comment]
The aliasing allows "Digital Playground Episodes" to have an alias of " Digital Playground", not all studios will follow the pattern of Network is used instead of studio name. You need to be very careful on changing this or you will cause others libraries to be overridden with incorrect scenes. The aliases allow when this rule should be applied.

It is not designed to match the TPDB data as the main page states the purpose, that what V2 does. You can not also use something like TPDP's namer, as TPDB and StashDB use different naming rules for scenes. StashDB is very strict if you have ever submitted metadata. If you want to use metadata from TPDB use V2.

"Whisparr is an adult movie collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new movies and will interface with clients and indexers to grab, sort, and rename them. It can also be configured to automatically upgrade the quality of existing files in the library when a better quality format becomes available. Note that only one type of a given movie is supported. If you want both an 4k version and 1080p version of a given movie you will need multiple instances."

**Comment by Eleniatari** [comment]
Will the user be allowed to assign these aliases within whisparr? 

According to stashdb, for any scene that is in a sub studio. The same exact scene can also be found in the main networks directory. 

So how would a scene matching the main network override any scene that it's not supposed to? Since every scene is present in the networks level directory? 

All the rules you have told me so far will prevent that from happening, either via date or scene name. Since any scene would either be the sub studio or the network per the filename.
