### ISSUE TITLE
V3: Performer Monitoring

### ISSUE THREAD

**Issue by Eleniatari** [Whisparr/Whisparr#180]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now, when a performer is monitored any studio that is 'available' in the library is marked as monitored. Any 'new' studio that is added is added in an unmonitored state.

### Describe the solution you'd like

Have the studio monitor option removed from the performer page. Just give the studio header and scenes. Making it clear that select scenes will be monitored.

This ties into this [issue](https://github.com/Whisparr/Whisparr/issues/179) where it would be great for the now 'unmonitored' scenes for the new studio to slowly populate in an unmonitored state without requiring the studio itself to be monitored.

### Describe alternatives you've considered

Give the option or make clear if 'new' scenes that are added on a performer refresh will be monitored, or unmonitored.

Right now, the flag on the studio is unmarked but the scene is marked. Causing conflicting information. Selecting the flag for the studio will monitor the entire studio.

### Anything else?

No

**Comment by plz12345** [comment]
Can you reproduce this behavior with a trace log on a performer with a small-ish scene count?  I deep dove the C# code for this, and what I see is:

1. When a movie is added, it has code to add the studio
2. The code to add the studio definitely sets Monitored to false if it's a new studio
3. The code to add a studio has logic to detect an existing studio, and if so, it uses that as-is to tie to the new scene, but I see nowhere where it updates that studio to be Monitored.

Please note step by step, alongside providing the log, so we can reproduce it locally.

**Comment by sampulsar** [comment]
@Eleniatari 

Do you want the want the tooltip to be changes, so you know if you click on the studio it will monitor the studio and then all of it scenes?

If a scene is monitored it is monitored in V3, there is no checking to see if the studio is also monitored. There is no confusing combinations and aligning of the moons. If a scene is monitored it is monitored.

Right now, the flag on the studio is unmarked but the scene is marked. "**Causing conflicting information**". Selecting the flag for the studio will monitor the entire studio.

**Comment by Eleniatari** [comment]
@sampulsar 

I would say remove the flag to monitor the studio from the performer page.

It leads to a conflicting user experiance where it appears that you must monitor the entire Studio in order to monitor the scenes for that performer.

**Comment by plz12345** [comment]
I had a comment not post. I propose making that flag just an indicator, rather than also clickable, as well as adding a tooltip to it as @sampulsar  noted. I can take that, if we have agreement.

**Comment by sampulsar** [comment]
An indicator is a good idea with an tooltip explanation. If you could also click on the studio name similar to the scene PR162, then you can navigate to the studio and turn on monitoring. You can then still look and a performer and then decide to monitor a studio in two clicks.

You then should not upset too many people.

**Comment by plz12345** [comment]
Yeah, that's what I had in mind.  I'll take this one.

**Comment by plz12345** [comment]
Take a look and let me know what you think.  I haven't submitted it yet.

**Comment by Eleniatari** [comment]
That can work. It does make it a bit more obvious.
