### ISSUE TITLE
Have other Metadata options then TMDB

### ISSUE THREAD

**Issue by boivinx7** [Whisparr/Whisparr#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

I would recommend the possibility of using https://metadataapi.net/ has an option to import videos and have metadata.
Also could link up in a way with PhoenixAdult metadata agent
https://github.com/PAhelper/PhoenixAdult.bundle

This way a lot could be imported but on your side it would there would be no meta to manage which i would imagine is the goal.
Then we could create auto downloads bases on sites or keywords.

Anyway, its a suggestion.

### Describe alternatives you've considered

I already Have RSS feeds in Deluge with some scripts for auto import.
This is just a suggestion

### Anything else?

nop

**Comment by bakerboy448** [comment]
Already in the works
https://github.com/Whisparr/Whisparr/tree/tpdb

**Comment by boivinx7** [comment]
> Already in the works https://github.com/Whisparr/Whisparr/tree/tpdb

nice!

**Comment by binarygeek119** [comment]
also the stashdb https://stashdb.org/ could be a go one too

**Comment by Protektor-Desura** [comment]
> also the stashdb https://stashdb.org/ could be a go one too

This one is invite only so it would NOT work. I tried to sign up and could not.

**Comment by Protektor-Desura** [comment]
So it looks like there are several databases you could pull from:
https://metadataapi.net/
https://metadataapi.net/docs
https://www.themoviedb.org/  (NEEDS MORE WORK/REFINEMENTS)

Might be able to eventually do some kind of plugin thing so you could scrape some of the big adult website of their data maybe? If they are plugins then other devs could keep them updated for web scrapping without the core system having to deal with web sites changing on you. Plugins would allow you to easily dump web scrappers that the community isn't keeping updated and easily dump sites that go down.

https://www.adultdvdempire.com/
https://www.data18.com/

https://github.com/imaginary-upside/JellyfinJav
https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult
https://github.com/adultplexdev/AdultDVDEmpire.bundle
https://github.com/adultmm/AdultMediaManager

**Comment by binarygeek119** [comment]
> > also the stashdb https://stashdb.org/ could be a go one too
> 
> This one is invite only so it would NOT work. I tried to sign up and could not.

its only invite tell it get to a better point then i will be open like tvdb. its still under development 
but stash will still need a account/api key

also head to the stash discord and get a invite key
![image](https://user-images.githubusercontent.com/72405030/182653836-631792bb-40b4-44bd-bbc7-df35ae2abb17.png)
`270b4c64-7b4a-4f6b-8d52-c222cf8e43f7
e02fbb73-12e0-47a2-bf26-958ee0a24d9c
4ffe4e7a-209b-4d21-bb7c-a9b6f60441b8
54d4a16d-65ef-46d5-87d0-30ddd31be5f1
0dfb24cb-d326-496a-93f3-dfa7926fd48a
8f6f69a6-09d7-4295-8645-48d247b048a8
9cde57ec-8559-46b3-8001-1bc49ae0a275
55c89650-23ad-430e-910a-f8ab718976bf
7a507740-027f-4d1e-9d12-85239f471f47
01310cde-2e05-4cb0-9a23-3f801c4030e2
018ef879-eb9f-40a4-a63f-7258a7e0bbe2
b991d79c-002d-44ee-bb54-db50e7f55c6a
6a48989a-1ebe-4b76-8aa1-400000d02d7e
176ae090-a65d-435a-b69e-8d9fc9bd8557`

**Comment by binarygeek119** [comment]
> So it looks like there are several databases you could pull from: https://metadataapi.net/ https://metadataapi.net/docs https://www.themoviedb.org/ (NEEDS MORE WORK/REFINEMENTS)
> 
> Might be able to eventually do some kind of plugin thing so you could scrape some of the big adult website of their data maybe? If they are plugins then other devs could keep them updated for web scrapping without the core system having to deal with web sites changing on you. Plugins would allow you to easily dump web scrappers that the community isn't keeping updated and easily dump sites that go down.
> 
> https://www.adultdvdempire.com/ https://www.data18.com/
> 
> https://github.com/imaginary-upside/JellyfinJav https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult https://github.com/adultplexdev/AdultDVDEmpire.bundle https://github.com/adultmm/AdultMediaManager

https://metadataapi.net/ is theporndb or tpdb. it has a weird url for now while its also being development. whitch at this point might not change anymore.

**Comment by MaienM** [comment]
It appears that TPDB now also has a StashBox endpoint (https://metadataapi.net/graphql), so support for that would cover both TPDB and StashDB, plus any other instances (like one that a user might be running themselves).

**Comment by furopi** [comment]
> It appears that TPDB now also has a StashBox endpoint (https://metadataapi.net/graphql), so support for that would cover both TPDB and StashDB, plus any other instances (like one that a user might be running themselves).

Thank you for that information, dear Sir!

**Comment by Qstick** [comment]
Done for v2
