### ISSUE TITLE
V3 performer search will search all scenes, not just monitored ones

### ISSUE THREAD

**Issue by plz12345** [Whisparr/Whisparr#200]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Monitor and refresh a performer
Unmonitor some of the scenes
Click Search Performer

Whisparr searches and downloads all scenes, not just monitored ones

### Expected Behavior

Whisparr only searches fur scenes that are monitored. 

### Environment

```markdown
- OS: 
- Whisparr: 3.0.0.523
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox
- Database: SQLite
```

### What branch are you running?

Develop

### Trace Logs?

Available if needed but this is easy to repro

**Comment by sampulsar** [comment]
Should be an easy fix to PerformersSearchService.cs

From 
var items = _movieService.GetByPerformerForeignId(performer.ForeignId);
to
var items = _movieService.GetByPerformerForeignId(performer.ForeignId).Where(x => x.Monitored).ToList();

**Comment by Tom-Estes** [comment]
Same for studios.
Do we want to skip search if the scene already has a file?

```
var items = _movieService.GetByPerformerForeignId(performer.ForeignId)
                                         .Where(x => x.Monitored &&
                                                     !x.HasFile)
                                         .ToList();
```

**Comment by plz12345** [comment]
> Same for studios. Do we want to skip search if the scene already has a file?
> 
> ```
> var items = _movieService.GetByPerformerForeignId(performer.ForeignId)
>                                          .Where(x => x.Monitored &&
>                                                      !x.HasFile)
>                                          .ToList();
> ```

No, that would negate upgrades, wouldn't it?

**Comment by Tom-Estes** [comment]
> No, that would negate upgrades, wouldn't it?

Good call.

**Comment by Tom-Estes** [comment]
> From var items = _movieService.GetByPerformerForeignId(performer.ForeignId); to var items = _movieService.GetByPerformerForeignId(performer.ForeignId).Where(x => x.Monitored).ToList();

Also in these if blocks so the search on the right side of the page works
if (message.StudioIds.Count > 0)
if (message.Years.Count > 0)

**Comment by plz12345** [comment]
Are you already working it, or want me to?  I just wasn't sure whether the fix should be in BE vs. FE. Now I know it's FE.

**Comment by Tom-Estes** [comment]
> Now I know it's FE. 

It's actually in the backend. If @sampulsar can do it, I can review it.

**Comment by plz12345** [comment]
Ah, ok.  Misread the post.

**Comment by sampulsar** [comment]
@Tom-Estes 

Can do. 

The filter is only for monitored, as there is a decision process that happens after this to allow upgrades, etc.

The studio search would also have the same issue, as the items do not look like they are filtered.

Filtering this list differently would not stop a user from manually searching for an individual item on any of the pages, studio, performer, or scene. A manual search there should always attempt to download the item.

**Comment by Tom-Estes** [comment]
> Filtering this list differently would not stop a user from manually searching for an individual item on any of the pages, studio, performer, or scene. A manual search there should always attempt to download the item.
>

I meant adding it to the if blocks also so it can filter the search for the whole studio if on the performer page, or year if on the studio page.
