### ISSUE TITLE
V3: When adding a scene, the cover does not show

### ISSUE THREAD

**Issue by plz12345** [Whisparr/Whisparr#202]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When clicking a scene in search results, the modal that previews the scene to be added and to select settings fails to show the scene's cover.  This is not an issue when adding a Movie.

<img width="580" alt="image" src="https://github.com/Whisparr/Whisparr/assets/132735020/242b5c7a-e298-490f-a384-d243a686f76a">

### Expected Behavior

Scene cover loads alongside the description.  This should use the same image `object-fit: cover;` CSS as the detail view for scenes to ensure images don't stretch.

### Steps To Reproduce

1. Go to Scenes > Add
2. Search and click on one that is not already in the library
3. Cover fails to load

### Environment

```markdown
- OS: Linux
- Whisparr: 3.0.0.530
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox
- Database: SQLite
```

### What branch are you running?

Main

### Trace Logs?

n/a, GUI-specific issue

### Anything else?

I may tackle this one myself, just wanted to log it in case I forget.

**Comment by Tom-Estes** [comment]
I got it working, but I want to clean up some existing code. There's a mix of inline styles, css not being used, sizes not being respected when passed down. I saw it before, but now is a good time to get it in control.
