### ISSUE TITLE
[v3] Endpoint to get scene via stashdb id

### ISSUE THREAD

**Issue by secondfolder** [Whisparr/Whisparr#218]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've written a little userscript that lets you quickly add a scene in stashdb to a local instance of whisparr (https://gist.github.com/secondfolder/e2d3edddaa75331786a1cfd20b76c074). However it needs to check if that scene has already been added to whisparr and if I'm understanding things right currently it's not possible to send the stashdb id of a scene to the api of a local whisparr instance and have it return that scene if it's been added.

 

### Describe the solution you'd like

Either a new `/scene/{whisparr id or stashdb id}` endpoint or an update to the slightly mislabeled (I'm assuming for legacy reasons) `/movie/{whisparr id}` endpoint to allow you to give it either a whisparr id or a stashdb id for a scene instead of just the local whisparr instance id.

### Describe alternatives you've considered

Currently I'm workaround the issue by hitting the https://your-local-whisparr-domain.com/api/v3/movies endpoint, fetching all scenes, then checking client-side if any scene matches the stash id. But that can obviously get very slow if you had a lot of scenes.

**Comment by sampulsar** [comment]
Alter the movieController so a single item can be returned similar to tmdbid

/api/v3/movie?stashId=0d26e902-daf6-4869-a89d-497a7cf278cd

[HttpGet]
public List<MovieResource> AllMovie(int? tmdbId, string stashId, bool excludeLocalCovers = false)
{
    var moviesResources = new List<MovieResource>();

    Dictionary<string, FileInfo> coverFileInfos = null;

    if (tmdbId.HasValue)
    {
        var movie = _moviesService.FindByTmdbId(tmdbId.Value);

        if (movie != null)
        {
            moviesResources.AddIfNotNull(MapToResource(movie));
        }
    }
    else if (stashId.IsNotNullOrWhiteSpace())
    {
        var movie = _moviesService.FindByForeignId(stashId);

        if (movie != null)
        {
            moviesResources.AddIfNotNull(MapToResource(movie));
        }
    }

**Comment by sampulsar** [comment]
This has been completed a while ago 

/api/v3/movie?stashId=0d26e902-daf6-4869-a89d-497a7cf278cd
