### ISSUE TITLE
[v3] Endpoint to check for releases of scene even if scene is only in stashdb and not (yet) in whisparr

### ISSUE THREAD

**Issue by secondfolder** [Whisparr/Whisparr#219]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've written a little userscript that lets you quickly add a scene in stashdb to your local instance of whisparr (https://gist.github.com/secondfolder/e2d3edddaa75331786a1cfd20b76c074). When you visit a scene page on stashdb it tries to work out if whisparr is able to download it or not by checking for releases for that scene. But in order to do that it first has to add that scene to whisparr.

I totally get if this ticket is just closed as "not planned" since I imagine it'd take a fair amount of reworking of whisparr internals and may well not be that useful to many other people. But I thought I may as well ask :)

### Describe the solution you'd like

It would be great if there was an API endpoint for a local instance of whisparr that you could give it a stashdb scene id and it would check for releases of that scene even if it hasn't been added to whisparr yet.

### Describe alternatives you've considered

At the moment I'm just adding every scene viewed in stashdb to whisparr in order to check releases for each scene. That works but it clutters up my local whisparr instance with lots of scenes that I may have not actual interest in fetching.

**Comment by sampulsar** [comment]
Alter the movieController so a single item can be returned similar to tmdbid 

/api/v3/movie?stashId=0d26e902-daf6-4869-a89d-497a7cf278cd

```
[HttpGet]
public List<MovieResource> AllMovie(int? tmdbId, string stashId, bool excludeLocalCovers = false)
{
    var moviesResources = new List<MovieResource>();

    Dictionary<string, FileInfo> coverFileInfos = null;

    if (tmdbId.HasValue)
    {
        var movie = _moviesService.FindByTmdbId(tmdbId.Value);

        if (movie != null)
        {
            moviesResources.AddIfNotNull(MapToResource(movie));
        }
    }
    else if (stashId.IsNotNullOrWhiteSpace())
    {
        var movie = _moviesService.FindByForeignId(stashId);

        if (movie != null)
        {
            moviesResources.AddIfNotNull(MapToResource(movie));
        }
    }
```

**Comment by nod44** [comment]
Interesting.  This is somewhat related the stash (app) suggestion I have in #112.   I think this kind of tool probably belongs as a userscript, but adding the endpoint seems to make sense for a number of reasons.

**Comment by plz12345** [comment]
I'd like this purely because there are scenes in StashDB that just never make it to Skyhook.

**Comment by sampulsar** [comment]
This is already available and used by stasharr it uses the search functionality 

lookup/scene?term=stash:${encodeURIComponent(stashId)}
