### ISSUE TITLE
connect app (stash)

### ISSUE THREAD

**Issue by binarygeek119** [Whisparr/Whisparr#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

be able to setup whisparr's connect tool to hook in to stash.
ideally be able to trigger a file scan and more (Scan, Identify, Auto Tag, Generate)
may have to submite a issue to stash's github to beable to connect this two apps together.
https://github.com/stashapp/stash

### Describe alternatives you've considered

not sure what esle to put here

### Anything else?

none

**Comment by thezak48** [comment]
Defo on the cards for v2

**Comment by Qstick** [comment]
Done in v2

**Comment by wranglatang** [comment]
Hello, Im not sure this works. Any time something gets downloaded I get an error in the log
```
Basic was not authenticated. Failure message: Authorization header missing.
```

**Comment by thezak48** [comment]
To use the API in Stash you have to enable authentication

![image](https://user-images.githubusercontent.com/1936903/228706540-8930dd75-d0da-4cae-8dba-ad9ea431fc09.png)

**Comment by wranglatang** [comment]
Thanks, this is what mine looks like 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/30660751/228781668-3892cf99-c7e4-4538-856d-2f54cde60c3d.png">

**Comment by wranglatang** [comment]
@thezak48 any ideas?
