### ISSUE TITLE
Monitoring Popular Performer Nearly Destroyed My Server

### ISSUE THREAD

**Issue by OrbitalStrudel** [Whisparr/Whisparr#225]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I recently discovered the ability to monitor performers. This feature is hidden away, likely for reasons like I experienced. I monitored a performer with hundreds of scenes. Whisparr began adding all the sites the performer created content with. Sometimes it worked and just picked up scenes the performer was in and nothing else. But on dozens of sites, it started searching for and adding ALL scenes from that site. Thousands and Thousands of scenes. It was a nightmare to try to unmonitor everything and prevent my server from melting down.

### Expected Behavior

Monitoring a performer will only download scenes from that performer, even when adding new sites.

### Environment

```markdown
- OS: Docker (nightly-067909e by hotio)
- Whisparr: 2.0.0.548
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

Not Sure

**Comment by Gykes** [comment]
If this is for V2, it's a known issue. 

V2 isn't getting developed anymore and no PR's are being accepted currently for V3 so it will continue to be an issue. 

The only way around, which is 100% a band-aid and not a fix, is to monitor the performer then set all the sites it adds to unmonitored or delete them after the correct scene is downloaded.

**Comment by OrbitalStrudel** [comment]
Yes. I'm using the "latest" build which is V2.

I'm in the process of migrating to the V3 build, which appears to have better Performer handling.

**Comment by nod44** [comment]
@OrbitalStrudel How did V3 work for you? Can this be closed?

**Comment by OrbitalStrudel** [comment]
V3 is still rough to use. Lots of missing features compared to V2. But it's usable. Let's close this.

For anyone trying to figure this out, V3 is the [eros branch](https://github.com/Whisparr/Whisparr/tree/eros). I'm running it on docker using the [hotio V3 builds](https://hub.docker.com/layers/hotio/whisparr/v3/images/sha256-5d95b801a45dca0695da759b1ec47b0d568d6f23baa29dd8209d75431c29f70c).
