### ISSUE TITLE
Integration with porndb.me api calls / rss feeds

### ISSUE THREAD

**Issue by lexisdude** [Whisparr/Whisparr#229]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Porndb.me is a truly solid source of new and backfill porn related videos, especially series videos. It would be nice to see some integration with the tool they have created in the indexers page. Perhaps it's already possible , but I have yet to figure out the correct settings allowing it to become a fully functional indexer. 

### Describe the solution you'd like

Integration into Whisparr as a functional indexer

### Describe alternatives you've considered

direct RSS feeds programmed into nzbget function with the site, A secondary tool, pdbmate that was written for the site is defunct when using with NZBGet 

### Anything else?

https://app.porndb.me/
https://github.com/pdbme/pdbMate

**Comment by Eleniatari** [comment]
I don't understand this request. You want to add porndb.me as an indexer? It does not support RSS so it won't work. In fact the entire benefit to porndb.me is that it does not use RSS feeds in their own words. 

> The major advantage with pdbMate download function in comparison to rss feeds is you do not get duplicates at all and you can specify prefered video qualities (video resolution). 

> Configured correctly you now have an automated download functionality setup for porn from usenet. As far as we know this has never been accompished before. Custom rss feeds where the best option you had until now.

Your entire request is to support a worse version of a program by a different program that does exactly what it does but better?

pdbMate is the same as whisparr except more basic.
https://github.com/stashapp/stash Stash already exists as an organizer and is far more reliable then file name organization. It already has integration into whisparr and tpdb.
https://github.com/ThePornDatabase/namer Namer already exits for renaming via phash with tpdb as the source.

Whisparr itself already support renaming and folderizing.
