### ISSUE TITLE
Erotic Audio 

### ISSUE THREAD

**Issue by binarygeek119** [Whisparr/Whisparr#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

be able to download Erotic Audio files (wav, mp3, ogg, m4b, m4a)

### Describe the solution you'd like

be able to download Erotic Audio files (wav, mp3, ogg, m4b, m4a)

### Describe alternatives you've considered

do it manually 

### Anything else?

no

**Comment by Protektor-Desura** [comment]
Only issue I see is where would you get them from or search for them plus pull the metadata from? Are you talking about basically audiobooks for adult books? If so then Goodreads API could do that.

If you are talking about adult books audiobooks that sounds more like something you would use Readarr for, for finding and downloading audiobooks.

https://readarr.com/
https://github.com/Readarr/Readarr

**Comment by Qstick** [comment]
Not in scope for now
