### ISSUE TITLE
Remove emoji and Unicode characters when matching text (title, performer)

### ISSUE THREAD

**Issue by sampulsar** [Whisparr/Whisparr#237]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There are some scene titles and performer names that contain an emoji, and these may not be present in the data being matched, indexer record / filename.

### Describe the solution you'd like

The normalisation should remove any special characters as the match can be done on the remaining text.

Other common substations can be normalised, such and replacing " & " with " and ", as this is a common substitution.

private static readonly Regex EmojiRegex = new Regex(@"\p{Cs}", RegexOptions.Compiled);
private static readonly Regex UniCodeRegex = new Regex(@"[^\u0000-\u007F]+", RegexOptions.Compiled); 

### Describe alternatives you've considered

manually altering files and looking for alternate indexer records, but better matching will automate the process.

### Anything else?

Example studio https://stashdb.org/studios/688dbbe8-8de9-4f60-a92b-570320dbcc99

**Comment by nod44** [comment]
@sampulsar is this on v3 (eros) or v2?

**Comment by sampulsar** [comment]
@nod44 

It can be done on both if required.

**Comment by sampulsar** [comment]
not required as a unit test was able to match
