### ISSUE TITLE
Erotic text stories 

### ISSUE THREAD

**Issue by binarygeek119** [Whisparr/Whisparr#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

be able to download Erotic text stories files (epub, mobi, pdf, txt)

### Describe the solution you'd like

be able to download Erotic text stories files (epub, mobi, pdf, txt)

### Describe alternatives you've considered

do it manually 

### Anything else?

no

**Comment by Protektor-Desura** [comment]
If you are talking about adult books that sounds more like something you would use Readarr for, for finding and downloading adult books.

https://readarr.com/
https://github.com/Readarr/Readarr

**Comment by Qstick** [comment]
Not in scope for now
