### ISSUE TITLE
V3: Match using character and not just performer name.

### ISSUE THREAD

**Issue by sampulsar** [Whisparr/Whisparr#244]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The title can match based on the Performers name as some items are listed with the performers name in the title section [studio] [date] [performers] and maybe the title [title]

There is existing code to check form this.

var cleanPerformers = movie.MovieMetadata.Value.Credits.Select(a => Parser.Parser.NormalizeEpisodeTitle(a.Performer.Name))
                                                                           .Where(x => x.IsNotNullOrWhiteSpace());

The performer may be listed as a different name on the site and this is stored in Whisparr V3. It is more likely that if there is a name for the performer then it is the character name, e.g. name on that site.

### Describe the solution you'd like

Add to the end of the matching that the character name should be checked. If they exist.

var cleanCharacters = movie.MovieMetadata.Value.Credits.Select(a => Parser.Parser.NormalizeEpisodeTitle(a.Character))
                                    .Where(x => x.IsNotNullOrWhiteSpace());

if (!cleanCharacters.Empty())
{
    // If parsed title matches performer Alias, consider a match
    if (cleanCharacters.Any(p => p.IsNotNullOrWhiteSpace() && parsedMovieTitle.Equals(p)))
    {
        matches.Add(movie);
        continue;
    }
}

var cleanFemaleCharacters = movie.MovieMetadata.Value.Credits.Where(a => a.Performer.Gender == Gender.Female)
                                          .Select(a => Parser.Parser.NormalizeEpisodeTitle(a.Character))
                                          .Where(x => x.IsNotNullOrWhiteSpace()).ToList();

if (!cleanFemaleCharacters.Empty())
{
    // If all female performers are in title, consider a match
    if (cleanFemaleCharacters.Any() && cleanFemalePerformers.All(x => parsedMovieTitle.Contains(x)))
    {
        matches.Add(movie);
        continue;
    }
}

### Describe alternatives you've considered

Look for another match

**Comment by Qstick** [comment]
Is this one you want to take yourself?
