### ISSUE TITLE
Windows - Removing Previous Service Fails; Installer Broken

### ISSUE THREAD

**Issue by bakerboy448** [Whisparr/Whisparr#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`C:\ProgramData\Whisparr\bin\Whisparr.Console.exe /u`

```
[Fatal] ConsoleApp: EPIC FAIL!

[v0.1.0.47] DryIoc.ContainerException: code: Error.UnableToResolveUnknownService;
message: Unable to resolve Microsoft.Extensions.Options.IOptions<NzbDrone.Core.Datastore.PostgresOptions> as parameter "postgresOptions" (IsSingletonOrDependencyOfSingleton)
  in Singleton NzbDrone.Core.Configuration.ConfigFileProvider: NzbDrone.Core.Configuration.IConfigFileProvider as parameter "configFileProvider" FactoryId=866 (IsSingletonOrDependencyOfSingleton)
```

https://discord.com/channels/957516730727563285/957516731654488087/983792895414927431

### Expected Behavior

Service Uninstall should work as expected

### Steps To Reproduce

Use the installer which gets stuck and fails at removing existing service or run the command manually

### Environment

```markdown
- OS: Windows 10
- Whisparr: v0.1.0.47
- Docker Install: No
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

Also needs backporting to all \*Arr postgres

**Comment by TetrisWolf** [comment]
if you go to task manager you can see whisper console under the whisparr installer, force close that whisparr.console and setup will be finished and working. no idea why though

**Comment by Qstick** [comment]
Fixed v2
