### ISSUE TITLE
[V3] Indexer - Add "Remove year from search string"

### ISSUE THREAD

**Issue by Eagle-NestIT** [Whisparr/Whisparr#255]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently a lot of movies/scenes are not found by the indexer(s) due to the fact that the year is passed to the search string.
In Radarr you have the option to enable "Remove year from search string" in the indexer configuration.

### Describe the solution you'd like

Add the option in the Indexer configuration to "Remove year from search string".

In Radarr the option is called:
Remove year from search string

And the description:
Should Radarr remove the year after the title when searching this indexer?

### Describe alternatives you've considered

Add the option in the Indexer configuration to "Remove year from search string".

In Radarr the option is called:
Remove year from search string

And the description:
Should Radarr remove the year after the title when searching this indexer?

**Comment by sampulsar** [comment]
@Eagle-NestIT 

Is this just #240 ?

**Comment by Eagle-NestIT** [comment]
> @Eagle-NestIT
> 
> Is this just #240 ?

Not completely.
Mine is mainly for the movies.
According to the logging it is searching below:
https://api.nzbgeek.info/api?t=search&cat=6010,6020,6030,6040,6050,6060,6070&extended=1&apikey=(removed)&offset=0&limit=100&q=Women%20Seeking%20Women%20142%202017

If I manyally perform the search with adding my apikey the result is indeed empty.

If I remove %202017 at the end it will find the movies without any issues.
https://api.nzbgeek.info/api?t=search&cat=6010,6020,6030,6040,6050,6060,6070&extended=1&apikey=(removed)&offset=0&limit=100&q=Women%20Seeking%20Women%20142

For movies removing the movie year in the search is a fix.
