### ISSUE TITLE
DownloadItemStatus mismatch with QBitTorrent API causing completed downloads to not be imported [v3]

### ISSUE THREAD

**Issue by enymawse** [Whisparr/Whisparr#260]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Whisparr logs present with the following message and completed downloads are not being imported:

`2024-10-09 07:52:25.5|Info|QBittorrent|Unknown download state: stoppedUP`

This also means the completed download is left in a `DownloadItemStatus.Downloading` state because it doesn't match any of the cases present at [QBittorrent.cs#L298](https://github.com/Whisparr/Whisparr/blob/a85a59122bd91cd75718ff4fbe4cf2df3a800687/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L298)

This happens because qBittorrent is giving the completed downloads a state of `stoppedUP` instead of what Whisparr is expecting of `pausedUP`

### Expected Behavior

Completed downloads should be imported.

### Steps To Reproduce

1. Using the latest version of Whisparr:V3 and [QBittorrent:5.0.0](https://github.com/qbittorrent/qBittorrent/releases/tag/release-5.0.0) as the configured download client.
2. Add a new scene to trigger a download using the configured download client
3. Download a torrent to completion
4. Once the torrent has completed, Whisparr logs will show the unknown download state

### Environment

```markdown
- OS: N/A
- Whisparr: 3.0.0.614
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
- Database: Sqlite 3.44.2
```

### What branch are you running?

eros

### Trace Logs?
[whisparr.trace.txt](https://github.com/user-attachments/files/17317347/whisparr.trace.txt)

### Anything else?

- QBittorrent download state changes [src/webui/api/serialize/serialize_torrent.cpp](https://github.com/qbittorrent/qBittorrent/commit/5d1c2496063b41874e85af0145b153e006fc92d3#diff-74790edbe4766657bffad7700b1a73f606a7692cee56f1e093c7357ecdaea915)

**Comment by edev-us** [comment]
This is happening with the latest version of Whisparr V2 2.0.0.548

Had to downgrade to qBittorrent 4.6.7 until this is fixed.

**Comment by enymawse** [comment]
> This is happening with the latest version of Whisparr V2 2.0.0.548
> 
> Had to downgrade to qBittorrent 4.6.7 until this is fixed.

Same. PR #261 should support both 4.6.7 and 5+. Unless the states get changed again.
