### ISSUE TITLE
Add app to YunoHost

### ISSUE THREAD

**Issue by DJPlaya** [Whisparr/Whisparr#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Request Details

Hi,

It would be great to have Whisparr as YunoHost App in the Future.
Similar Apps like Sonarr/Radarr/Prowlarr/Lidarr/Bazarr are already integrated, so packing should be easy.
Information can be found here > https://yunohost.org/en/packaging_apps

Thank you

**Comment by ta264** [comment]
Distribution specific packages would be provided by the distribution / their contributors rather than us
