### ISSUE TITLE
File on disk for scenes is wrong

### ISSUE THREAD

**Issue by gujikabeepbop** [Whisparr/Whisparr#281]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

For some scenes (I don't know what is the culprit) the size on disk is 0B. The size on disk of the file is correct. Nothing standing out in info logs. If I update info, the size of the scene becomes correct in the frontend but refreshing the page makes it 0B again.

### Expected Behavior

Size on disk is correct

### Environment

```markdown
- OS: linux
- Whisparr: eros
- Docker Install: yes
- Using Reverse Proxy: yes
```

### What branch are you running?

eros

### Trace Logs?

I don't see anything in info logs, cannot provide trace logs for now.

**Comment by sampulsar** [comment]
@gujikabeepbop 

Is this 
V3 - eros
V2 - develop

**Comment by gujikabeepbop** [comment]
It's V3 - eros branch

**Comment by 2pnk1stnk** [comment]
I'm seeing this issue too. v3

![SOD](https://github.com/user-attachments/assets/9bb93b0e-0ae6-40eb-8398-caf6eb8e4f4d)
