### ISSUE TITLE
[v3] Add a New Section in the left side menu for "Clips" which would use FansDB as its endpoint

### ISSUE THREAD

**Issue by 2pnk1stnk** [Whisparr/Whisparr#302]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

A new section for "Clips" since I assume we want to differentiate from 'Scenes'
starting to build up a collection of items that were produced as OF content

### Describe alternatives you've considered

there really is no alternative, currently

### Anything else?

don't know how likely, difficult, or possible this is, but gotta start the discussion somewhere

**Comment by sampulsar** [comment]
@2pnk1stnk 

It is better to have a separate instance of Whisparr as the IDs for performers are different between each Stash. This also requires that SkyHook (the server that provides Whisparr the metadata to supply the data). There needs to be the data first as Whisparr requires that the data is transformed into a usable format first as it does not directly connect to StashDB.org.

**Comment by 2pnk1stnk** [comment]
@sampulsar 

So it's a hard-stop limitation? Bummer. If this needs to be closed as a result, so be it. Thanks.
