### ISSUE TITLE
Add support for stashdb. Also add support for pulling "tag" info for scenes. 

### ISSUE THREAD

**Issue by aarons3225** [Whisparr/Whisparr#308]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There is a problem with the difference in information between stashdb and tpdb. I have also seen duplicate videos for certain sites like Primal on tpdb.

### Describe the solution you'd like

Just add support for stashdb as well as an info provider. I would also love to see importing the tags from stashdb or tpdb for scenes so as to be able to only monitor scenes that have xyz performer, AND a specific tag i.e. anal, or threesome, or whatever.  Maybe add it under the performers part and format it similar to the performers section in whisper
<img width="1279" alt="whisparr scene" src="https://github.com/user-attachments/assets/19b19baf-a845-4f5f-aa3f-af205a436fa2">
<img width="905" alt="stashdb scene" src="https://github.com/user-attachments/assets/e34a8d92-729b-47b9-ba85-e55c953f3cdd">

### Describe alternatives you've considered

I've thought about using tags in whisparr, however, that is a manual adding of tags to every scene. It also wouldn't help filter monitoring of new scenes.

**Comment by plz12345** [comment]
V2 is TPDB, v3 is StashDB.  The two won't be mixed. V3 does not sync tags,thoug there is a pending change to block tags via import lists.

**Comment by sampulsar** [comment]
@aarons3225 

The data is retrieved as a Genres for V3 that is using StashDB as the metadata source.

https://api.whisparr.com/v4/scene/375fe33a-d4a5-4b86-8af6-b55d909e7358

**Comment by aarons3225** [comment]
So then what I need to look at is the V3 version. Awesome thank you!
