### ISSUE TITLE
[V2]: Unable to communicate with SkyHook.

### ISSUE THREAD

**Issue by somename9** [Whisparr/Whisparr#326]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Searching fails:
![image](https://github.com/user-attachments/assets/eb22dbda-a53c-4d6a-bf91-46508c491514)

### Expected Behavior

Search works

### Steps To Reproduce

- Use ghcr.io/thespad/whisparr:latest docker container
- Search

### Environment

```markdown
- OS: Unraid
- Whisparr: v2.0.0.548
- Docker Install: ghcr.io/thespad/whisparr:latest
- Using Reverse Proxy: No
- Browser: Firefox
- Database: No idea
```

### What branch are you running?

v2

### Trace Logs?

[trace.txt](https://github.com/user-attachments/files/18239649/trace.txt)

**Comment by locke69321** [comment]
This is a known issue, cache is being rebuilt, but there is no ETA. Access is likely to be spotty at best until it's done.

**Comment by somename9** [comment]
Is it normal that updating existing sites also fails?

**Comment by locke69321** [comment]
The cache no longer exists, they are rebuilding it from TPDB, until it's rebuilt, any metadata is probably spotty and possibly incomplete.

**Comment by amaeru16** [comment]
how can we add a site in the meanwhile?

**Comment by TheLinuxGuy** [comment]
It would be nice if whisparr.com had a status page about API maintenance... and it would be so great if there was backup API...

**Comment by plz12345** [comment]
> It would be nice if whisparr.com had a status page about API maintenance... and it would be so great if there was backup API...

Infrastructure costs money.  Donate if you want more out if it.

**Comment by Qstick** [comment]
Metadata was resource limited, it's been bumped up now, but cache will take some time to rebuild with the TPDB rate limiting.
