### ISSUE TITLE
Bulk edit List Folders

### ISSUE THREAD

**Issue by derpindialer** [Whisparr/Whisparr#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I would like to be able to bulk edit the folder for Lists. I removed a root directory and have a bunch of lists still pointing to that directory. In the movies bulk editor, you can bulk change directories easily. Can this be implemented for lists?

### Describe alternatives you've considered

Manual editing of lots of lists is very time consuming.

### Anything else?

![image](https://user-images.githubusercontent.com/82851376/194644857-d064d1a7-36a3-4d1b-8b90-09e9b475a4cf.png)

**Comment by Qstick** [comment]
https://github.com/Whisparr/Whisparr/commit/ea5ba1f845e83b068ea7b38c029acdcdb8e9bb5c
