### ISSUE TITLE
Needs Actor, Actress, and studio Subscription method

### ISSUE THREAD

**Issue by argash** [Whisparr/Whisparr#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I've seen a few mentions in other issues of searching for these things but I think this is big enough that it needs it's own request. Basically it's 2022 and porn is more often released as single scenes with only a handful of actors/actresses these days. Yes DVDs/BRs are released but it's a small minority of the available content. 

### Describe the solution you'd like

To make this app truly useful it needs to let the user "subscribe" to specific actors/actresses and even studios. Bonus points if the user can subscribe to keywords (asian, milf, teen, you get the point).

### Describe alternatives you've considered

right now we have to manually do this with Prowlarr

### Anything else?

I'm free to answer any questions.

**Comment by knoxysam** [comment]
@argash how do you subscribe in prowlarr?

**Comment by EXCIDIVM** [comment]
I am surprised this request isn't discussed more.
I understand that Whisparr has to build on the fundamentals of Radarr/Sonarr. But as it stands, the functionality would have been helpful in the late 90's and early 2000's, but doesn't accomodate the reality of the adult industry in 2023.

**Comment by bionic-steve** [comment]
Could porndb.me be used to feed the searches?
e.g. 

With porn stars set up, might be able to search based on one of their rss feeds

My Pornstars | https://api.porndb.me/rss/mypornstars?apikey=XXX&minQuality=720p

**Comment by snoopyra** [comment]
Would also like to suggest this as a feature. The current functionality is largely unworkable due to the industry practices (as mentioned in previous comments). Having the ability to subscribe to particular actors/actresses would make the application far more practical.

**Comment by HotBlack77** [comment]
Just wanted to say that I complete agree, the core functionality must be to subscribe to specifc actress or studios and then ideally filter by keyword tags. 
However, I can see why this is tricky; performers have aliases, their name may be a pre/post fix of anothers name and there is really no cannonical source of perfomeres the way there is with IMDB and TVDB for movies and tv. Perhaps IAFD could be used to pull performer info?

**Comment by i-am-at0m** [comment]
The way it's handled in Stash is it's looked up on either TSDB or TPDB, which includes pulling aliases.

**Comment by thezak48** [comment]
tpdb is our metadata provider and we have no plans to pull from anywhere else for the time being. this is currently being worked on however we still have a few things to work out

**Comment by MRobi1** [comment]
Actor/Actress and studio subscriptions are when this app will really take off. It's current functionality doesn't provide much based on the current state of the industry. 

I would recommend the ability to pull metadata from stashdb as well. It's got a very large db and is community maintained with the ability to selfhost your own stashdb server. Plus I would assume the majority of Whisparr users will also be Stash users since none of Plex/Emby/Jellyfin really properly support adult content. 

Neither StashDB or TPDB are complete, but using both they get pretty close. The issue I see with multiple metadata providers will be filtering out duplicate scenes when there are slight differences between the 2 db's. So I wouldn't expect something like this until the rest of the core functions are up and working. Call it a future feature request.

**Comment by salesawagnerpe** [comment]
There is a PR for this, but apparently it was abandoned
[New: Monitor performers via Lists](https://github.com/Whisparr/Whisparr/pull/48)

**Comment by thezak48** [comment]
Not abandoned

**Comment by DarthDMFH** [comment]
Since the majority of scenes within sites have Performer names, would it be possible to index this column to find scenes for specific people across all sites in our individual implementations?

**Comment by spencerdf1992** [comment]
Maybe a monitor drop down? 
1) Monitor all
2) Monitor for performer
3) Not Monitorred

For option 2, the scene would become monitored if the a performer named matched a list similar to a release profile tag.
