### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by MrMxyzptlk** [Whisparr/Whisparr#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No issues.

### Describe the solution you'd like

Collections exactly like in Radarr. They also have the option to monitor movies and collections in a list.

A lot of adult films are a series...such as Emmanuelle.

### Describe alternatives you've considered

No alternates.

### Anything else?

Just reference Radarr.

**Comment by Qstick** [comment]
Not applicable to v2
