### ISSUE TITLE
FR: IAFD support

### ISSUE THREAD

**Issue by mgaulton** [Whisparr/Whisparr#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No 

### Describe the solution you'd like

No

### Describe alternatives you've considered

None

### Anything else?

No

**Comment by bakerboy448** [comment]
IAFD?

**Comment by mgaulton** [comment]
> 

Internet Adult Film Database. IMDB for adult movies.

**Comment by cpt-cunnilingus** [comment]
+1 I agree with @mgaulton, TMDB and IMDB are not sufficient sources for metadata.

Just keep in mind IAFD mainly accounts for western content. I would also suggest we look into supporting JAV content as well.

perhaps we could utilise something like: https://github.com/iamrony777/javinfo-api

I was thinking I could start a PR using the tool above or finding something similar.

It really depends how we want to take this approach, do we go for a self hosted scraping approach? or use an external API?

Really open to discussion here.

**Comment by austinwbest** [comment]
I believe v2 meta discussion revolved around tpdb as the meta source since it pulls from many places and aggregates the data already

**Comment by cpt-cunnilingus** [comment]
@austinwbest what is the tpdb? as in the poster database? o.0

edit: i dont think it covers JAV content very well.

**Comment by austinwbest** [comment]
The porn database.. Confusing, I know lol

Metadataapi.net iirc

**Comment by cpt-cunnilingus** [comment]
oh thats pretty good, doesn't cover all JAV but its a good start.

**Comment by austinwbest** [comment]
> oh thats pretty good, doesn't cover all JAV but its a good start.

yea, they have a good amount of data, scrape a lot of sites, support scenes (something whisparr would be able to do at that point), etc and i believe are pretty open to adding more sources of data to scrape from.

**Comment by cpt-cunnilingus** [comment]
yup thats pretty cool, im speaking to the devs there to help out scraping their hentai and jav content.

**Comment by Qstick** [comment]
Closing this or v2
