### ISSUE TITLE
Add movie by company folder

### ISSUE THREAD

**Issue by baloodusudouest** [Whisparr/Whisparr#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

To organize the movie by company first, and after by movie

### Describe the solution you'd like

In the media management, possibility to have for ex: (Company Name)/{Movie Title} ({Release Year})

### Describe alternatives you've considered

None

### Anything else?

Nope

**Comment by Qstick** [comment]
This will be done in v2
