### ISSUE TITLE
Super long naming issue

### ISSUE THREAD

**Issue by minermartijn** [Whisparr/Whisparr#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some videos have super long names. eg Japanese movies.
And searching for them does not result in any video.

### Describe the solution you'd like

Is there a way to have them search for the alternative names? Because they do give results.

### Describe alternatives you've considered

.

### Anything else?

.

**Comment by Qstick** [comment]
Not Applicable to v2
