### ISSUE TITLE
Studio hierarchy on V2

### ISSUE THREAD

**Issue by baloodusudouest** [Whisparr/Whisparr#45]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Studios have multiple sub studios, or series (for ex: Mindgeek is a major distributors, MEN is a studio, The Gay Office is a sub studio or series)
I would like to have for ex the hability on the episode naming site folder format to have {Distributor}/{Studio}/{Sub Studios}

### Describe the solution you'd like

I would like to have for ex the hability on the episode naming site folder format to have {Distributor}/{Studio}/{Sub Studios}

### Describe alternatives you've considered

Done it manually

**Comment by thezak48** [comment]
Added this to the already existing feature request #15
