### ISSUE TITLE
Use Stash DB as metadata source

### ISSUE THREAD

**Issue by ThatDeltaGuy** [Whisparr/Whisparr#57]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

TMDB isnt really set up to handle scenes, compelations, amature movies ect. and where it is it's incomplete most of the time. Stash DB is basically TMDB but for Porn and it's kept up to date with a large community. 
I'm also not sure adding entire studios is the way to go, I'd rather search to add individual scenes and treat them like radarr does movies. for the fuctionality that adding studios gives you'd be better using Lists.

### Describe the solution you'd like

Working with Stash DB to pull metadata from them, maybe expanding the fields they store ect. 

### Describe alternatives you've considered

There isnt really any alterative

### Anything else?

Heres the github for the self-hosted version of stashdb https://github.com/stashapp/stash-box

**Comment by thezak48** [comment]
We no longer use TMDB for metadata, v2 uses TPDB https://metadataapi.net/ now
