### ISSUE TITLE
Manual Import doesn't automatically match files if over 100 files in folder

### ISSUE THREAD

**Issue by Keysersose12** [Whisparr/Whisparr#63]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In my import folder i have over 100 files and none are automatically recognised when the folder is selected using the manual import option. If i got to the events section it says "Unable to determine series from folder name and found more than 100 files. Skipping parsing". If i reduce the files in the folder to below 100 then files are automatically recognised/matched.

### Expected Behavior

Whisparr is able to automatically match files when using the manual import option and there is over 100 files in the folder

### Steps To Reproduce

1. Have over 100 files in your import folder
2. Go to wanted section and select manual import option
3. Select your import folder and click interactive import
4. No files are automatically matched and as a result the import option is not selectable

### Environment

```markdown
- OS: Windows 10
- Whisparr: 2.0.0.139
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

N/A

**Comment by Qstick** [comment]
This is intended behavior
