### ISSUE TITLE
Re: Stash - Add: Identify task

### ISSUE THREAD

**Issue by kzndotsh** [Whisparr/Whisparr#65]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently provided Connection options:
- Generate Covers
- Generate Previews
- Generate Image Previews
- Generate Sprites
- Generate Phashes

I would love to see "Identify Scene" added as an option.

### Describe the solution you'd like

Identify is essentially a way to match a scene based on either Phash or naming scheme/etc and will fall back to the users default Identify settings iirc. I imagine there is an API call for this.

If a user likes to match with Phash and Stash DB for example as their identify source then this identify task via whisparr should be ran AFTER the "Generate Phashes" is finished to achieve possible matching

### Describe alternatives you've considered

not sure, maybe a script/curl command to run if no api call works

**Comment by kzndotsh** [comment]
Also worth noting that because Whisparr works with TPDB, this could be a great feature for working with the TPDB Stash scraper as an identify source as well.

**Comment by JoeNyland** [comment]
I'd like to see this added, too.

Here's the GraphQL query that can be used to initiate the identify task:

```graphql
mutation identify {
  metadataIdentify(input:{
    sources: [
      { source:{ stash_box_endpoint: "https://stashdb.org/graphql" } }
      { source:{ scraper_id: "builtin_autotag" } }
    ]
    options: {
      fieldOptions: [ 
      	{
          field: "Title"
          strategy: OVERWRITE
          createMissing: true
        },
      	{
          field: "Studio Code"
          strategy: MERGE
        }, 
      	{
          field: "Date"
          strategy: MERGE
        }, 
      	{
          field: "Director"
          strategy: MERGE
        }, 
      	{
          field: "Details"
          strategy: MERGE
        }, 
      	{
          field: "URL"
          strategy: MERGE
        }, 
      	{
          field: "Studio"
          strategy: MERGE
          createMissing: true
        }, 
      	{
          field: "Performers"
          strategy: MERGE
          createMissing: true
        }, 
      	{
          field: "Tags"
          strategy: MERGE
          createMissing: true
        }, 
      	{
          field: "Stash IDs"
          strategy: MERGE
        },
      ]
      setCoverImage: true
      setOrganized: true
      includeMalePerformers: false
    }
    paths: ["/path/to/media"]
  })
}
```

I would also follow this up to update performers, too, as although the above identify task creates the performers, it doesn't download the associated metadata for them.

Here's the query to update performers:

```graphql
mutation updatePerformers {
  stashBoxBatchPerformerTag(input:{
    endpoint: 0,
    exclude_fields: ["Name"]
    refresh: true
  })
}
```

**Comment by AnonumousMouse** [comment]
I wish I saw this earlier. Having the query already would have saved a lot of troubleshooting/learning. Either way, I have added a crude first pass of this feature in the following pull request https://github.com/Whisparr/Whisparr/pull/82.

**Comment by PrivatePasta** [comment]
StashDB requires an invite to join so I would suggest adding a notice to the dialogue box for adding this task, telling users to create an account on StashDB (invites can be found on StashApp's discord) or they'd be stuck only using AutoTag, which is nowhere close to StashDB.
