### ISSUE TITLE
[Feature Request] StashBox as metadata source 

### ISSUE THREAD

**Issue by aicynide** [Whisparr/Whisparr#69]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Nope

### Describe the solution you'd like

It would be faster than tpdb since we add be able to match file hash like anidb

### Describe alternatives you've considered

https://traxxx.me

**Comment by Qstick** [comment]
No plans to use stash for metadata right now, TPDB syncs phashs with stash. We've talked about supplementing in the future from stash
