### ISSUE TITLE
Error: Couldn't map movie %MOVIE_NAME% on The Movie DB. It will not be added :(: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mooangus** [Whisparr/Whisparr#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I am getting the following error when trying to add a TMDB List with a Keyword.  The error is as follows:

Error: Couldn't map movie %MOVIE_TITLE% on The Movie DB. It will not be added :(: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 tmdbId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 93
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 281

This is happening with any keyword number I try.  For example: URL https://www.themoviedb.org/keyword/155262-threesome/movie.  Keyword number: 155262.

It looks like it is an issue with the call to https://api.whisparr.com/v1 not returning valid information.

### Expected Behavior

Add the titles associated with the keyword number.

### Steps To Reproduce

Go to Lists, Add TMDB List by keyword number, Enter keyword number 155262, Review error log.

### Environment

```markdown
- OS: Debian 11.3
- Whisparr: 0.1.0.27
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Safari
```

### What branch are you running?

Nightly

### Trace Logs?

[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/8526858/whisparr.trace.txt)
[whisparr.txt](https://github.com/Whisparr/Whisparr/files/8526859/whisparr.txt)
[whisparr.debug.txt](https://github.com/Whisparr/Whisparr/files/8526860/whisparr.debug.txt)

**Comment by Qstick** [comment]
Needs `include_adult` in the tmdb calls, and some filters to only try mapping results if adult=true
