### ISSUE TITLE
Performer import list triggers Season monitoring when "Specific Episodes" is selected

### ISSUE THREAD

**Issue by plz12345** [Whisparr/Whisparr#96]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using the Performer Import List feature, the Monitor Specific Episodes feature also monitors the Seasons those episodes are in.  This leads to the downloading of undesired releases added to those seasons later on when the Series data is refreshed from TPDB and new episodes are added to the season.

### Expected Behavior

Monitor Specific Episodes should only enable monitoring for the episodes matching the import list performer ID, not the seasons the episode resides in.

### Steps To Reproduce

1. Add a performer list that is for a performer currenltly releasing new content
2. Look for sites added by the import list
3. Not that any releases that were mointored are also showing within seasons that were also enabled for monitoring (futur releases, not all episodes in the season)

### Environment

```markdown
- OS: Linux
- Whisparr: 2.0.0.241
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome and Firefox
```

### What branch are you running?

Develop

### Trace Logs?

To repro, I added a performer import list for Performer ID 164444 (Octavia Red)

[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/12246150/whisparr.trace.txt)

**Comment by PAHelper2** [comment]
Still seeing this in version 2.0.0.250

**Comment by plz12345** [comment]
> Still seeing this in version 2.0.0.250

This isn't marked as fixed yet so obviously it wasn't fixed in that version.

**Comment by Cyno01** [comment]
Yup, took me a while to figure out what was going on with performers i didnt know showing up in stash. 

After disabling and enabling and redisabling a bunch of stuff and playing around with adding import lists, any sites added by a list, it will monitor only the relevant existing videos when the list is created, but it will monitor any and all future releases on that site, so day 1 you get the three videos from the one performer you wanted, day 2, you get all that sites releases from day 1 and 2... You go from 200 wanted videos to 2000 the next day. 

So same issue with 2.0.0.269 (nice) on baremetal windows install.

**Comment by DasGreff** [comment]
I have the same issue here, just made a script using the api to unmonitor what I don't want

**Comment by Ey3scr34m** [comment]
> I have the same issue here, just made a script using the api to unmonitor what I don't want

Sounds awesome. Do you mind sharing until the issue is fixed?

**Comment by DasGreff** [comment]
Sure @Ey3scr34m : https://pastebin.com/BNgjZG2N

**Comment by DasGreff** [comment]
This is insane, i have more than 148190 scenes in my wanted list since update in v2.0.0.287

**Comment by salesawagner** [comment]
following

**Comment by bboyles303** [comment]
following

**Comment by bboyles303** [comment]
> I have the same issue here, just made a script using the api to unmonitor what I don't want

Tried that script but seems to fail with parse error: Invalid numeric literal at line 1, column 10

**Comment by plz12345** [comment]
@Qstick 
I don't think this is resolved in your recent improvements to the list handling flow.  I have one configured per below, and when it added a new site, both the desired scene and the 2023 season were monitored.  This would result in the behavior this issue is about to keep occurring.

<img width="742" alt="image" src="https://github.com/Whisparr/Whisparr/assets/132735020/cc6b7741-f80d-42ef-8110-45aab71a2e0e">

**Comment by Qstick** [comment]
Not necessarily, the site ignores the season monitoring if the setting for new items is set appropriately. If you actually see the behavior not working, then we can dive into it on Discord

**Comment by plz12345** [comment]
Circling back to note this hasn't recurred.  I bulk reset this setting to "none" on all my Sites, and have not seen any unexpected downloads since.
