### ISSUE TITLE
Add Prowlarr as an Indexer

### ISSUE THREAD

**Issue by XargonWan** [Whisparr/Whisparr#97]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Please add the option of adding Prowlarr as an Indexer

### Describe the solution you'd like

Indexers -> Add Indexer -> Prowlarr

### Describe alternatives you've considered

None

### Anything else?

Thanks in advance!

**Comment by bakerboy448** [comment]
- Why is this needed?
- What problem would this solve?
- There's 0 reason why Prowlarr needs its own entry nor does this request make any sense.
- Prowlarr is Torznab and more importantly - you simply add the apps to Prowlarr which then syncs the indexers itself to the apps as applicable based on your configuration in prowlarr of indexers / tags / indexer categories / app sync categories

**Comment by thezak48** [comment]
Prowlarr already supported

**Comment by XargonWan** [comment]
> * Why is this needed?
> * What problem would this solve?
> * There's 0 reason why Prowlarr needs its own entry nor does this request make any sense.
> * Prowlarr is Torznab and more importantly - you simply add the apps to Prowlarr which then syncs the indexers itself to the apps as applicable based on your configuration in prowlarr of indexers / tags / indexer categories / app sync categories

Actually it's not working, I tried via Prowlarr and via Torznab (even Newznab).



![2023-08-18_10-42](https://github.com/Whisparr/Whisparr/assets/6771419/03b5b7c3-110c-4207-a6e9-c40f1c0acac9)
![2023-08-18_10-41](https://github.com/Whisparr/Whisparr/assets/6771419/e505dd30-b1bc-4f44-bcf1-29a99a76aee5)
![2023-08-18_10-40](https://github.com/Whisparr/Whisparr/assets/6771419/0e9123b1-2196-46e9-b91e-7b9ed693dbbf)
