### ISSUE TITLE
Restrictions?

### ISSUE THREAD

**Issue by jasonxwashere** [Whisparr/Whisparr#99]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

https://wiki.servarr.com/whisparr/settings#restrictions references allowing restrictions at the indexer setup but does not appear to be present.  Would like to restrict certain file types (via naming convention is fine).

### Describe the solution you'd like

Ability to add restrictions to downloads.

### Describe alternatives you've considered

I'm not sure that there are any?

### Anything else?

Currently running 2.0.0.243

**Comment by Qstick** [comment]
This is done via custom formats or release profiles now. Docs just need updating
